import qrcode
import io
import base64
from typing import Optional
from loguru import logger


class QRService:
    @staticmethod
    def generate_qr_code(data: str, size: int = 10) -> str:
        qr = qrcode.QRCode(
            version=1,
            error_correction=qrcode.constants.ERROR_CORRECT_H,
            box_size=size,
            border=4,
        )
        qr.add_data(data)
        qr.make(fit=True)

        img = qr.make_image(fill_color="black", back_color="white")
        buffer = io.BytesIO()
        img.save(buffer, format="PNG")
        buffer.seek(0)

        b64 = base64.b64encode(buffer.getvalue()).decode("utf-8")
        return b64

    @staticmethod
    def generate_sensor_qr(api_key: str, endpoint_url: str = "https://api.aquapulse.ai") -> str:
        data = f"{endpoint_url}/api/sensors/reading|{api_key}"
        return QRService.generate_qr_code(data)

    @staticmethod
    def generate_qr_pdf(api_key: str, sensor_name: str, village_name: str, endpoint_url: str = "https://api.aquapulse.ai") -> bytes:
        from reportlab.lib.pagesizes import A4
        from reportlab.lib.units import cm
        from reportlab.pdfgen import canvas as pdf_canvas

        buffer = io.BytesIO()
        c = pdf_canvas.Canvas(buffer, pagesize=A4)
        width, height = A4

        c.setFont("Helvetica-Bold", 20)
        c.drawCentredString(width / 2, height - 3 * cm, "AquaPulse AI - Sensor Node QR")

        c.setFont("Helvetica", 12)
        c.drawCentredString(width / 2, height - 4.5 * cm, f"Sensor: {sensor_name}")
        c.drawCentredString(width / 2, height - 5.5 * cm, f"Village: {village_name}")

        qr_b64 = QRService.generate_sensor_qr(api_key, endpoint_url)
        qr_bytes = base64.b64decode(qr_b64)
        qr_buffer = io.BytesIO(qr_bytes)

        from reportlab.lib.utils import ImageReader
        qr_image = ImageReader(qr_buffer)
        qr_size = 10 * cm
        c.drawImage(qr_image, (width - qr_size) / 2, height - 18 * cm, qr_size, qr_size)

        c.setFont("Helvetica", 9)
        c.drawCentredString(width / 2, height - 19 * cm, f"API Key: {api_key[:8]}...{api_key[-4:]}")
        c.drawCentredString(width / 2, height - 20 * cm, f"Endpoint: {endpoint_url}/api/sensors/reading")

        c.setFont("Helvetica-Oblique", 8)
        c.drawCentredString(width / 2, 2 * cm, "Scan this QR code to configure the sensor node.")
        c.drawCentredString(width / 2, 1.2 * cm, "Generated by AquaPulse AI System")

        c.save()
        buffer.seek(0)
        return buffer.getvalue()
